### ISSUE TITLE
Failing tests 

### ISSUE THREAD

**Issue by martingold** [Machy8/Grid#11]
Tests are failing on fresh clone from master. It most likely caused by different font rendering in Webkit on Ubuntu and adjusting test treshold may help.

Steps to reproduce:
```
git clone ...
cd Grid
npm install
npm run css-tests
```

Enviroment:
Ubuntu 17.04
npm 5.0.3

Here is the [output](https://github.com/Machy8/Grid/files/1145628/tests.txt) of tests.
And [here](https://github.com/Machy8/Grid/files/1145639/actual.tar.gz) is the "actual"  folder with PhantomJS image outputs if that helps

**Comment by Machy8** [comment]
I am considering removing the phantomJs tests because of the same problem as you said. I will find another way to test the framework.
